name: 'aws-profile-web-identity'
description: 'Get a Github token and do some magic'
inputs:
  aws-profile-source:
    description: 'AWS profile source'
    required: true
    default: 'credentials.aws'
  aws-token-file-location:
    description: 'AWS Web Identity Token file location'
    required: true
    default: '~/.aws/web_identity_token_file'
runs:
  using: "composite"
  steps:
    - run: mkdir -p ~/.aws
      shell: bash          
    - run: cp ${{ inputs.aws-profile-source }} ~/.aws/credentials
      shell: bash            
    - run: curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' > ${{ inputs.aws-token-file-location }}
      shell: bash
