name: 'aws-profile-web-identity'
description: 'Get a Github token and do some magic'
inputs:
  aws-profile-source:
    description: 'AWS profile source'
    required: true
    default: 'credentials.aws'
  aws-token-file-location:
    description: 'AWS Web Identity Token file location'
    required: true
    default: '~/.aws/web_identity_token_file'
  actions-id-token-request-token:
    description: 'some token'
    required: true
  actions-id-token-request-url:
    description: 'some request'
    required: true   
runs:
  using: "composite"
  steps:
    - run: mkdir -p ~/.aws
      shell: bash          
    - run: cp ${{ inputs.aws-profile-source }} ~/.aws/credentials
      shell: bash            
    - run: curl -s -H "Authorization: bearer ${{ inputs.actions-id-token-request-token }}" "${{ inputs.actions-id-token-request-url }}&audience=sts.amazonaws.com" | jq -r '.value' > ${{ inputs.aws-token-file-location }}
      shell: bash
